apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scsctl.fullname" . }}
  labels:
    {{- include "scsctl.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scsctl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scsctl.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scsctl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: create-postgres-datbase
          image: "docker.io/bitnami/postgresql:16.0.0-debian-11-r13"
          imagePullPolicy: Always
          command:
          - "/bin/sh"
          - "-c"
          - >
            echo "Creating database {{ .Values.postgresql.database }} if it does not exist..." &&
            psql -h {{ .Values.postgresql.host }} -p {{ .Values.postgresql.port }} -U {{ .Values.postgresql.username }} -lqt | cut -d \| -f 1 | grep -qw {{ .Values.postgresql.database }} || psql -h {{ .Values.postgresql.host }} -p {{ .Values.postgresql.port }} -U {{ .Values.postgresql.username }} -c "CREATE DATABASE {{ .Values.postgresql.database }};" &&
            echo "Database {{ .Values.postgresql.database }} created or already exists. Listing all databases:" &&
            psql -h {{ .Values.postgresql.host }} -p {{ .Values.postgresql.port }} -U {{ .Values.postgresql.username }} -l &&
            sleep 5
          env:
          - name: PGPASSWORD
            {{- if not .Values.postgresql.existingSecret }}
            value: "{{ .Values.postgresql.password }}"
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.existingSecret.name }}
                key: {{ .Values.postgresql.existingSecret.passwordKey }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          args:
            - server
          env:
          - name: SCSCTL_PG_HOST
            value: "{{ .Values.postgresql.host }}"
          - name: SCSCTL_PG_PORT
            value: "{{ .Values.postgresql.port }}"
          - name: SCSCTL_PG_USER
            value: "{{ .Values.postgresql.username }}"
          - name: SCSCTL_PG_PASSWORD
            {{- if not .Values.postgresql.existingSecret }}
            value: "{{ .Values.postgresql.password }}"
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.existingSecret.name }}
                key: {{ .Values.postgresql.existingSecret.passwordKey }}
            {{- end }}
          - name: SCSCTL_PG_DATABASE
            value: "{{ .Values.postgresql.database }}"
          - name: SCSCTL_ENVIRONMENT
            value: "{{ .Values.env.SCSCTL_ENVIRONMENT }}"
            
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
