name: Renovate

on:
  push:
    branches: [ "feat/renovate" ]
  pull_request:
    branches: [ "feat/renovate" ]
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
