name: scsctl_test
on:
  push:
    branches: [ test/scsctl_cicd_integration ]
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Pull pyroscope/pyroscope:latest image 
      run: docker pull pyroscope/pyroscope:latest

    - name: Run pyroscope 
      run: docker run -d -it -p 4040:4040 pyroscope/pyroscope:latest server

    - name: Install a python cli tool from test pypi  and run it
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple scsctl
    - name: Install k3s and run Helm chart
      run: |
        curl -sfL https://get.k3s.io | sh -
        sleep 60
        kubectl get pods

    - name: run scsctl --help
      run: |
        scsctl scan --pyroscope_app_name pyroscope.server --docker_image_name pyroscope/pyroscope:latest --pyroscope_url http://localhost:4040 --non_interactive
