name: scsctl_test
on:
  push:
    branches: [ test/scsctl_cicd_integration ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Pull pyroscope/pyroscope:latest image 
      run: docker pull pyroscope/pyroscope:latest

    - name: Install a python cli tool from test pypi  and run it
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple scsctl

    - name: run scsctl --help
      run: |
        scsctl scan --pyroscope_app_name pyroscope.server --docker_image_name pyroscope/pyroscope:latest --pyroscope_url https://369d-111-92-44-131.ngrok-free.app --non_interactive