name: scsctl_test
on:
  push:
    branches: [ test/scsctl_cicd_integration ]
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Pull pyroscope/pyroscope:latest image 
      run: docker pull pyroscope/pyroscope:latest

    - name: Run pyroscope 
      run: docker run -d -it -p 4040:4040 pyroscope/pyroscope:latest server

    - name: Start a local k8s cluster
      uses: jupyterhub/action-k3s-helm@v3
      with:
        # See available:
        # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
        # - k3s versions at https://github.com/k3s-io/k3s/tags
        # - helm versions at https://github.com/helm/helm/tags
        k3s-channel: latest
        # k3s-version: v1.22.2+k3s1
        # helm-version: v3.7.0

    - name: Verify function of k8s, kubectl, and helm
      run: |
        echo "kubeconfig: $KUBECONFIG"
        kubectl version
        kubectl get pods --all-namespaces

        helm version

        # helm install falco -f custom-rules.yaml --set "falco.rules_file={/etc/falco/falco_rules.local.yaml,/etc/falco/rules.d}" --set falcoctl.artifact.install.enabled=false --set falcoctl.artifact.follow.enabled=false --set falco.json_output=true --set falco.file_output.enabled=true falcosecurity/falco
    - name: Run pyroscope in k3s
      run: |
        helm repo add pyroscope-io https://pyroscope-io.github.io/helm-chart
        helm install pyroscope pyroscope-io/pyroscope

        # export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=pyroscope,app.kubernetes.io/instance=pyroscope" -o jsonpath="{.items[0].metadata.name}")
        # export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
        
        # sleep 30

        # kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

        # kubectl get pods


        # curl http://localhost:4040
    - name: List pods
      run: |
        kubectl get pods

    # - name: Install a python cli tool from test pypi  and run it
    #   run: |
    #     python -m pip install --upgrade pip
    #     python -m pip install --upgrade build
    #     python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple scsctl
    # - uses: debianmaster/actions-k3s@master
    #   id: k3s
    #   with:
    #     version: 'latest'
    # - run: |
    #     kubectl get nodes
    #     helm install falco -f ./custom-rules.yaml \  
    # --set "falco.rules_file={/etc/falco/falco_rules.local.yaml,/etc/falco/rules.d}" \
    # --set falcoctl.artifact.install.enabled=false \
    # --set falcoctl.artifact.follow.enabled=false \
    # --set falco.json_output=true \
    # --set falco.file_output.enabled=true \
    # falcosecurity/falco

    # - name: run scsctl --help
    #   run: |
    #     scsctl scan --pyroscope_app_name pyroscope.server --docker_image_name pyroscope/pyroscope:latest --pyroscope_url http://localhost:4040 --non_interactive
